name: social-network
services:
  traefik:
    image: "traefik:v3.4"
    container_name: "social-network-traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - social-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./letsencrypt:/letsencrypt"
    environment:
      - CF_DNS_API_TOKEN=your_cloudflare_api_token
    labels:
      - "traefik.enable=true"
  go-app:
    build:
      context: ../../
      dockerfile: deployment/local_full/golang/Dockerfile
    container_name: go-app
    networks:
      - social-network
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgres://user:password@db:5432/social_network?sslmode=disable
    working_dir: /app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-app.rule=Host(`highload-social-network.romasmi.com`)"
      - "traefik.http.routers.go-app.entrypoints=websecure"
      - "traefik.http.routers.go-app.tls.certresolver=myresolver"
      - "traefik.http.services.go-app.loadbalancer.server.port=8000"
  db:
    image: "postgres:16-alpine"
    container_name: "social-network-db"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - social-network
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Remove ports for security in production
volumes:
  db:
  redis:
networks:
  social-network: