global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'social-network-api'
    static_configs:
      - targets: ['api:8888']
  - job_name: 'social-network-worker'
    static_configs:
      - targets: ['worker:8889']
